hooks/tk-multi-publish2/basic/publish_variants.py

Upload thumbnail in sg_thumbnail when publishing variants

[SHOT-3257] Fill both the thumbnail and the attachment fields on the Note entity

---

hooks/tk-multi-loader2/basic/scene_actions.py
hooks/tk-multi-shotgunpanel/basic/scene_actions.py

* Rename 'texture_node' action label "Import into Scene" to "Create Canvas". This is intended for 2D published file types:  JPEG, PNG, PSD, TIF, BMP.

[SHOT-3464] Rename "Import into Scene" to "Create Canvas"

---

engine.py
hooks/tk-multi-snapshot/basic/scene_operation.py
hooks/tk-multi-workfiles2/basic/scene_operation.py
python/tk_alias/alias_event_watcher.py

Added a method to the engine to call a list of Alias API functions while blocking any event callbacks until all operations are complete. This resolves issues that occur when a file is in the middle of opening and Alias callbacks trigger other python code to execute.

Defer Alias callbacks until all API operations have completed

---

hooks/tk-multi-publish2/basic/publish_session.py

* Allow publishing a file that has references whose paths do not exist on local disk
* Display a non-blocking warning message in the publisher log if invalid references found

SHOT-3904: bug fix validate reference paths on publish #84

---

hooks/tk-multi-loader2/basic/scene_actions.py
hooks/tk-multi-shotgunpanel/basic/scene_actions.py

Pass param `True` to Alias Python API function to load canvas onto construction plane, if one is picked at creation time, else it will load it oriented toward the current camera.

SHOT-2950: Load image onto Construction plane

---

azure-pipelines.yml
python/tk_alias/scene_data_validator.py

* Remove the "collapse" action for individual layers, as it causes issues due to dependencies
* Add dependency "zero transforms" to "layer has single item" (geometry may be re-parented and affects the geometry if it has not had zero transform applied to it before hand)
* Update "delete empty sets" wording to clarify "selection sets"
* Add item action to individual layers to select their geometry for "layer has single item"

SHOT-4030: SDV fix for collapsing a single layer

---

README.md
engine.py
python/tk_alias/__init__.py
python/tk_alias/dialog_parent.py

Revert "Remove the DialogParent class. Instead use the base Toolkit Engine method to get the dialog parent. (#93)"
* This reverts commit fea704cd8b912ecbaa19c961e24799abad954d51.
* We need this dialog class to find the Alias window since Alias is not yet using Qt.
* If this dialog class is not used to find the parent, we cannot properly parent the SG Toolkit windows.

SHOT-4059: Add back dialog class

---

hooks/tk-multi-publish2/basic/publish_annotations.py

1. If we are not background processing or are in the background process, then we get the note links to include in creating the annotation notes.
2. If we are background processing and in the background process, then we do not get note links to attach, BUT we continue to create annotation notes (without note links).
@barbara-darkshot In **2.** we continue to create the annotation notes even though we do not have access to the note links. Is this the intended behaviour?

SHOT-4044: Fix local variable 'note_links' referenced before assignment error.

---

hooks/tk-multi-loader2/basic/scene_actions.py
hooks/tk-multi-shotgunpanel/basic/scene_actions.py

* Improve error message to include link to Alias help doc
* Show the import subdiv option without checking if the function exists in the API - the API should throw an Alias version compatibility error if it is not supported

[SHOT-3713]: Improve import subdiv action handling

---

python/tk_alias/alias_event_watcher.py

* ContextManager on exit should start listening for Alias events again, even when ignore_events is True
* This bug caused Alias events to be ignored forever until user turns it back on themselves

Fix listening for Alias events

---

python/tk_alias/data_validator.py

Data validation performance regression found for dag node checks. The issue is caused by processing nodes one by one, instead of using the more performant Alias Python API traverse methods (which was caused by the data validation app passing the full list of nodes to the fix functions, instead of None which used to indicate to process all nodes).

SHOT-4162: Fix data validation performance

---

hooks/tk-multi-workfiles2/basic/scene_operation.py

* Save the context for the stage on reset when parent action is new file
* This fixes updating the context correctly when opening a new file from workfiles
* Return False when the file was not opened, this is to ensure the context does not change to the file that was requested to be opened, but was not opened

Fix saving the context for Alias stage.

---

startup.py

@rob-aitchison this will modify Alias software found by the launcher, which will not show Alias < 2022.0
Did we want this, or do we prefer a less aggressive method to indicating minimum version support?

Update minimum supported version to 2022.

---

engine.py
hooks/tk-multi-publish2/basic/collector.py
hooks/tk-multi-publish2/basic/upload_version.py
startup.py

* Use new Alias Python API function to generate an image of the current Alias viewport
* Set the publish default thumbnail to the current Alias viewport and show it in the publish screenshot widget UI
* Allow user to override default thumbnail by using screen grab widget
* Do not use thumbnails generated by LMV

SHOT-4306/SHOT-4321: LMV translation updates and improve thumbnails on publish

---

startup.py

* Without specifying encoding on file open, Python will use the system default encoding (typically utf-8) and if any invalid characters are found, it will not raise UnicodeError, but instead will repalce any invalid characters with a Unicode replacement
* Some users may experience errors on file open if their system default encoding is not utf-8. To make sure this works for all users, explicitly define the encoding and replace errors with Unicode replacements.
* Additionally, add extra fallback step to try a more lenient encoding "latin-1"

SG-33518:  Fix Alias startup failure on reading AboutBox.txt file

---

hooks/tk-multi-publish2/basic/upload_version.py
info.yml

* Requires v1.x.x due to framework breaking change
* Only validate the framework exists when performing 3D publish (2D does not use the framework and so not required)

Add tk-framework-lmv requirement

---

hooks/menu_customization.py
info.yml
python/tk_alias/menu_generation.py

* Allow order of ShotGrid menu items to be customized via a new hook
* Default ordering remains unchanged (sorted alphabetically by command app name, then command name)

SHOT-4105: Add hook to customize ShotGrid menu.

---

hooks/tk-multi-publish2/basic/upload_version.py

* Must include thumbnail image in LMV package for ShotGrid to use this image as the Version thumbnail

SHOT-4306: Include thumbnail in LMV package

---

info.yml

tk-framework-alias v1.2.0 required for:
* Alias 2025.0 PySide6 support
* Fix Alias 2024.1 plugin restart bug

Update tk-framework-alias min version

---

engine.py
python/tk_alias/menu_generation.py

* Always remove the ShotGrid menu on destroy - it can be recreated on start up if the engine is destroyed because of a restart

SHOT-4357: Fix menu on SG restart engine and apps

---

engine.py
python/tk_alias/menu_generation.py

* Remove menu on destroy. Menu can be recreated on restart.
* Alias < 2024.0 does not hae 'menu.remove()' method. Use clean up instead.

Release v3.0.4

---

hooks/tk-multi-data-validation/basic/scene_operations.py
python/tk_alias/data_validator.py

* Provides warning messages when the VRED scene has changed to indicate validation/fix may be stale

SHOT-4158: Add hook for data validation auto refresh based on alias scene events.

---

engine.py
info.yml

* Ensure tk-framework-alias is initialized when running tk-alias headless (this is done in startup.py prepare_launch when running Alias with UI, e.g. from FPT Desktop)

SHOT-4375: Fix running tk-alias headless

---

engine.py

* Need to initialize the placeholder text color (default is black, and not very visible)

SHOT-4392: Fixes for Alias with Qt6

---

python/tk_alias/shotgrid_alias_client.py

* Currently the Alias engine is not shut down properly when Alias is force closed causing FPTR to fail to start up the next time launched
* Ensure the FPTR qt app is exited and Alias Engine is shut down when Alias is force closed
* Qt app quit will trigger the engine shutdown

SHOT-4396: Shut down Alias Engine properly

---

startup.py

Introducing `win32api.GetLogicalDriveStrings()` to get the list of available drive letters in Windows.
In terms of performance, `win32api.GetLogicalDriveStrings()` is generally very fast and efficient. It directly interfaces with the Windows API to get the list of logical drives, which is a relatively quick operation. 
Regarding the `glob` search, I've done lookup tests with a few different drive letters and it works with no major difference in performance.
Install Alias software in a different drive than C:. SGD should be able to locate the software and add its icon normally.

SG-36346 Dynamic hard drive lookup in windows

---

hooks/tk-multi-publish2/basic/publish_session.py

* Validate will fail and provide error message if publish mode is set to 'Export Selection' but nothing is selected
* User will not be able to publish until at least one object is selected in the Alias scene
* This is to avoid the user publishing selection with nothing selected, which results in Alias not saving a file at all

SHOT-4430: Block publish Export Selection if nothing selected

---

docs/v4.1.8.rst
hooks/tk-multi-loader2/basic/scene_actions.py

* Context manager was introduced to execute actions in batch to improve performance time of executing actions, but we cannot use the context manager here since it gathers all Alias Python API request within the context and only executes them after the context has exited; however, an action may need to get the result of the Alias Python API request immediately in order to execute the main action function

SHOT-4450: Fix loader actions in Alias

---

engine.py
startup.py

Differentiate warning messages between the oldest compatible version and the oldest supported version.
- shotgunsoftware/tk-3dsmax#49
- shotgunsoftware/tk-houdini#81
- shotgunsoftware/tk-mari#30
- shotgunsoftware/tk-maya#122
- shotgunsoftware/tk-motionbuilder#36
- shotgunsoftware/tk-nuke#116
- shotgunsoftware/tk-vred#134
Note: Please ignore the exact versions in the screenshots below. I had to tweak the code to issue those. 
* Error message when VRED version is older than the oldest **compatible** version
* Warning message when VRED version is older than the oldest **supported** version
* Warning message when VRED version is newer than the newest **supported** version

SG-32814 Review and unify code handling supported DCC versions
