- startup.py
Added args cleanup step
Added AutoStudio as FALLBACK CODE NAME
> [SHOT-3262] Alias Auto Discovery Logic doesn't support other install naming.

- hooks/tk-multi-publish2/basic/publish_translation.py
Added while routing for sharing the thumbnail
> [SHOT-3193] Empty description field for Alias translations

- README.md
- hooks/tk-multi-shotgunpanel/basic/scene_actions.py
- python/tk_alias/win_32_api.py
Just a first pass for python-modernize
> [SHOT-3021-STEP-1] Move engines to pyside 2 and python 3 

- README.md
Updated README file to be aligned with shotgun standard
> [SHOT-3300] Align README.md files for tk-alias

- hooks/tk-multi-snapshot/basic/scene_operation.py
Removed unused operations from snapshot hook
> [SHOT-3251] Context lost after loading a snapshot in Alias

- startup.py
- startup/start.py
> [SHOT-3711] Added path releases for 2021.2.1 and 2021.2.2 in startup.py.

- hooks/tk-multi-publish2/basic/publish_session.py
- hooks/tk-multi-publish2/basic/publish_translation.py
- hooks/tk-multi-publish2/basic/start_version_control.py
This PR replaces ZD urls to AKN and developer urls
> SG-21170 [ZD to AKN] Update links referenced from code to the old support site to point to AKN

- .gitignore
- .pre-commit-config.yaml
- engine.py
- hooks/tk-multi-snapshot/basic/scene_operation.py
- hooks/tk-multi-workfiles2/basic/scene_operation.py
This is probably the reason why Jenkins job for the Alias Python API could not push the new `alias_api_om.pyd` to this repo.
> Update .gitignore to not ignore the alias_api pyd files.

- docs/hooks.rst
- hooks/tk-multi-data-validation/basic/scene_data_validation.py
- python/tk_alias/scene_data_validator.py
@rob-aitchison let me know what you think of this as an example for how to add a new rule to the validation
> Provide example to Scene Data Validation hook to adda new custom rule

- .coveragerc
- .gitignore
- python/tk_alias/scene_data_validator.py
- tests/fixtures/config/env/test.yml
* Add codecov to tk-alias now that there are unit tests.
* Remove extra quotes while we're here
Not sure why Codecov report is not shown in the PR as in other git repos with Codecov added.
> Add Codecov

- api/alias_py/pick_list.py
> SHOT-4034: Fix bug related to selecting geometry

- api/alias_py/traverse_dag.py
**Change Log**
- Fix Alias Python API exception class name
(The rest of the features already merged since `develop` branch just introduced)
> Release v2.1.7

- python/tk_alias/alias_event_watcher.py
- python/tk_alias/scene_data_validator.py
* Allow `kwargs` field to be dynamic (change from static value to function that returns the value)
* Minor bug fixes related to event watcher
> SHOT-4097: Data validation updates

- engine.py
- hooks/tk-multi-loader2/basic/scene_actions.py
Add fallback code to loading the project config folder if it has not yet been loaded and cached.
> Shot 4221: Fix get pipeline config

- engine.py
- hooks/tk-multi-publish2/basic/publish_session.py
- hooks/tk-multi-publish2/basic/publish_translation.py
- hooks/tk-multi-publish2/basic/start_version_control.py
* SHOT-4276: Fix publish error message (#160)
> Release v3.0.1

- engine.py
- startup.py
* Do not assume a project context on start up. Instead get the entity from the context in order of Task, Entity, Project
Related to https://github.com/shotgunsoftware/tk-shotgun-launchpublish/pull/18
> SHOT-4323: Open published file using SG Toolkit Action "Open in Associated App"

- engine.py
- hooks/menu_customization.py
- hooks/tk-multi-publish2/basic/collector.py
- hooks/tk-multi-publish2/basic/publish_translation.py
- hooks/tk-multi-publish2/basic/upload_version.py
- hooks/tk-multi-shotgunpanel/basic/scene_actions.py
- info.yml
- python/tk_alias/menu_generation.py
- software_credits
- startup.py
* #167
* #171 
* #172
* #174 
* #177 
* #178 
* #179 
* #180 
* #181
> Release v3.0.3

- README.md
- SECURITY.md
- docs/index.rst
- engine.py
- hooks/menu_customization.py
- hooks/tk-multi-loader2/basic/scene_actions.py
- hooks/tk-multi-publish2/basic/publish_annotations.py
- hooks/tk-multi-publish2/basic/publish_session.py
- hooks/tk-multi-publish2/basic/publish_translation.py
- hooks/tk-multi-publish2/basic/publish_variants.py
- hooks/tk-multi-publish2/basic/publish_vred.py
- hooks/tk-multi-publish2/basic/upload_version.py
- hooks/tk-multi-shotgunpanel/basic/scene_actions.py
- info.yml
- python/tk_alias/menu_generation.py
- python/tk_alias/shotgrid_alias_client.py
- python/tk_alias/shotgrid_alias_client_namespace.py
- startup.py
Change all the shotgrid/shotgun occurrences in the repository.
> SG-34683 - Rebranding

- hooks/tk-multi-breakdown2/basic/actions.py
* Add remove reference file action to Breakdown2 file items
> SHOT-4292: Add custom actions in Breakdown2

- hooks/tk-multi-breakdown2/basic/actions.py
- info.yml
* Update supported version to 2025.0 for Alias
* Add custom action support for Scene Breakdown
> Release v3.2.0

- hooks/tk-multi-data-validation/basic/scene_operations.py
- python/tk_alias/data_validator.py
* Update Data Validation UI based on Alias events
> Release v3.3.0

- engine.py
- python/tk_alias/dialog_parent.py
- startup.py
* Updates to support Python 3.11 and PySide6
> SHOT-4387: Python 3.11 and PySide6 support

- python/tk_alias/alias_py/dag_node.py
- python/tk_alias/alias_py/layer.py
- python/tk_alias/alias_py/pick_list.py
- python/tk_alias/data_validator.py
- python/tk_alias/menu_generation.py
- Replaced ensure_* functions.
- New import for ensure_* functions
- six types replaced by native python types
> SG-35870 FIRST PHASE python2 removing

- docs/changes.rst
- docs/v4.1.2.rst
- engine.py
- info.yml
- python/tk_alias/framework_alias.py
- python/tk_alias/shotgrid_alias_client.py
* Increase default timeout for socketio client
* Improve error handling of Qt errors on start up
> SHOT-4407: Improve Alias start up

- engine.py
- hooks/menu_customization.py
- hooks/tk-multi-breakdown2/basic/actions.py
- hooks/tk-multi-data-validation/basic/scene_operations.py
- hooks/tk-multi-publish2/basic/collector.py
- hooks/tk-multi-publish2/basic/publish_session.py
- hooks/tk-multi-publish2/basic/publish_translation.py
- hooks/tk-multi-publish2/basic/publish_vred.py
- hooks/tk-multi-publish2/basic/upload_version.py
- python/tk_alias/alias_py/dag_node.py
- python/tk_alias/alias_py/layer.py
- python/tk_alias/alias_py/pick_list.py
- python/tk_alias/alias_py/utils.py
- python/tk_alias/menu_generation.py
- python/tk_alias/shotgrid_alias_client.py
- python/tk_alias/shotgrid_alias_client_namespace.py
- tests/test_menu_generation.py
- tests/test_scene_data_validator.py
- Conditionals for Python 2 removed.
- Super format updated.
- Publish
> SG-38064 - Python 2 code removal
